In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd
import numpy as np

import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)

from sklearn.metrics import accuracy_score


In [ ]:
# pip install tensorflow==2.7.0.

In [ ]:
# Load dataset
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
path = '/content/drive/MyDrive/abc/dataset.csv'
dataset = pd.read_csv(path)
# Indipendent Variables
X_train= dataset.iloc[0:5,0:2].values
print(X_train)
# Dependent Variables
Y_train= dataset.iloc[0:5,2].values
print(Y_train)
print("############")
# Indipendent Variables
X_test= dataset.iloc[5:7,0:2].values
print(X_test)
# Dependent Variables
Y_test= dataset.iloc[5:7,2].values
print(Y_test)

[[50 55]
 [55 60]
 [60 65]
 [48 53]
 [62 67]]
[0 0 1 1 0]
############
[[72 77]
 [42 47]]
[1 0]


In [ ]:
model = keras.Sequential()
model.add(layers.Dense(2, activation="relu"))
model.add(layers.Dense(3, activation="relu"))
model.add(layers.Dense(3, activation="relu"))
model.add(layers.Dense(2))

In [ ]:
model.compile(optimizer='sgd', loss='mse', metrics=['accuracy'])
# This builds the model for the first time:
model.fit(X_train, Y_train, batch_size=2, epochs=200)

Epoch 1/200
3/3 [==============================] - 0s 5ms/step - loss: 493.5558 - accuracy: 0.4000
Epoch 2/200
3/3 [==============================] - 0s 5ms/step - loss: 0.6080 - accuracy: 0.4000
Epoch 3/200
3/3 [==============================] - 0s 5ms/step - loss: 0.5834 - accuracy: 0.4000
Epoch 4/200
3/3 [==============================] - 0s 5ms/step - loss: 0.5602 - accuracy: 0.4000
Epoch 5/200
3/3 [==============================] - 0s 4ms/step - loss: 0.5388 - accuracy: 0.4000
Epoch 6/200
3/3 [==============================] - 0s 4ms/step - loss: 0.5252 - accuracy: 0.4000
Epoch 7/200
3/3 [==============================] - 0s 4ms/step - loss: 0.5085 - accuracy: 0.4000
Epoch 8/200
3/3 [==============================] - 0s 4ms/step - loss: 0.4945 - accuracy: 0.4000
Epoch 9/200
3/3 [==============================] - 0s 4ms/step - loss: 0.4770 - accuracy: 0.4000
Epoch 10/200
3/3 [==============================] - 0s 4ms/step - loss: 0.4607 - accuracy: 0.4000
Epoch 11/200
3/3 [=========

In [ ]:
y_pred = model.predict(X_test, batch_size=2)
print(y_pred)
y_pred1D = y_pred.argmax(1)
print(y_pred1D)
print (Y_test)

1/1 [==============================] - 0s 87ms/step
[[0.40561518 0.4069409 ]
 [0.40561518 0.4069409 ]]
[1 1]
[1 0]


In [ ]:
print(accuracy_score(Y_test,y_pred1D))

0.5


In [ ]:
model.save('/content/drive/MyDrive/abc/mymodel1')

In [ ]:
model1 = keras.models.load_model('/content/drive/MyDrive/abc/mymodel')

y_pred = model1.predict(X_test, batch_size=2)
print(y_pred)
y_pred1D = y_pred.argmax(1)
print(y_pred1D)
print (Y_test)

1/1 [==============================] - 0s 109ms/step
[[0.3938016 0.3938016 0.3938016 0.3938016]
 [0.3938016 0.3938016 0.3938016 0.3938016]]
[0 0]
[1 0]


In [ ]:
!pip install flask-ngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install pyngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 761.3/761.3 KB 14.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pyngrok: filename=pyngrok-5.2.1-py3-none-any.whl size=19792 sha256=9294a67aeed9dc9073e5341f598783eaacedf2c0824ca2e3a6c175e40c5203cc
  Stored in directory: /root/.cache/pip/wheels/5d/f2/70/526da675d32f17577ec47ac4c663084efe39d47c826b6c3bb1
Successfully built pyngrok


In [ ]:
from flask import Flask
from pyngrok import ngrok
ngrok.set_auth_token("2K5XJE4Uufsi0kXznTRSD799aIW_5zMt8qeGdjdKjgE3JP6db")

In [ ]:
from flask_ngrok import run_with_ngrok
from flask import Flask

app=Flask(__name__)

run_with_ngrok(app)

@app.route("/")
def index():
  return "This is my first website <h1> Hello World Ali Saeed</h1>";
app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


 * Running on http://b45c-34-125-137-143.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


INFO:werkzeug:127.0.0.1 - - [11/Jan/2023 09:56:24] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [11/Jan/2023 09:56:24] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [11/Jan/2023 09:56:24] "GET /cart.json HTTP/1.1" 404 -


SyntaxError: ignored